### ISSUE TITLE
Create a Demo Environment

### ISSUE THREAD

**Issue by Urquhart83** [architecture-topography/topo#5]

**Comment by joeyhotz** [comment]
CircleCI aws user currently cannot access the s3 bucket without giving it administrator access which is not preferable.

**Comment by jagregory** [comment]
TL;DR: the aws-cli in apt is super old, and doesn't properly support downloading files which are KMS encrypted. e.g. https://github.com/aws/aws-cli/issues/1014

The fix is to install aws-cli from pip, which is the latest version.

**Comment by jagregory** [comment]
I've updated the IAM role for the CI user and upgraded aws-cli, which has got us further... however, `docker-machine` isn't available in Circle, so we need to figure out how to push to our remote docker. Probably need to manually set the `DOCKER_HOST` env variables
